# Generated by Django 2.2.7 on 2019-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='Guta', max_length=100),
        ),
    ]
