# Generated by Django 2.2.7 on 2019-11-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='open',
            new_name='active',
        ),
    ]
