# Generated by Django 2.2 on 2019-11-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191112_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='images/default.png', height_field=400, upload_to='images', width_field=400),
        ),
        migrations.AlterField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
