# Generated by Django 2.2 on 2019-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191114_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
    ]
