# Generated by Django 2.2 on 2019-11-17 18:46

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191117_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=models.ImageField(default='D:\\MyWorkSpace\\Python\\Shop_Raluca\\backend\\media\\albums_image\\default', upload_to=shop.models.get_image_path),
        ),
    ]
