# Generated by Django 2.2 on 2019-11-17 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20191117_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='albums',
        ),
        migrations.CreateModel(
            name='AlbumToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Album')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='albums_quantity',
            field=models.ManyToManyField(to='shop.AlbumToCart'),
        ),
    ]
