# Generated by Django 2.2 on 2019-11-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20191117_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='albums_quantity',
            new_name='albums_and_quantity',
        ),
    ]
