# Generated by Django 2.2 on 2019-11-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20191117_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='albums_and_quantity',
        ),
        migrations.AddField(
            model_name='albumtocart',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
    ]
